### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by aarvndhNG** [Leader-txt/TShockPlugin-Shop#11]
![Screenshot_20230104-162809](https://user-images.githubusercontent.com/107058543/210541392-ae8d28d9-177c-467f-b561-d6b43d22ba4e.png)

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by ACaiCat** [comment]
What is caused it?

**Comment by ACaiCat** [comment]
> @ACaiCat

Could you send me the config of shop?

**Comment by aarvndhNG** [comment]
> > @ACaiCat
> 
> Could you send me the config of shop?

It's already gone when i send this screenshot

**Comment by aarvndhNG** [comment]
And i need one more thing

**Comment by aarvndhNG** [comment]
@ACaiCat can you add section by section like blocks are subtracted and weapons are subtracted like that

**Comment by aarvndhNG** [comment]
#
![Screenshot_20230105-123608](https://user-images.githubusercontent.com/107058543/210721795-b4a6dec2-01ad-4113-8b46-7cef316bf67d.png)

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by ACaiCat** [comment]
I'm a little busy recently. I will repair him as soon as possible

**Comment by LaoSparrow** [comment]
`System.OutOfMemoryException` ?🤔
We need more information about that.
Could you provide us with your log file?
You may download it from your server management website. (not sure if your site provides this kind of features)
Or otherwise you have to capture the whole `Exception`

<img width="880" alt="image" src="https://user-images.githubusercontent.com/60737561/211122218-4d155f27-38ab-4bcc-b08e-22f56f75a736.png">
Like this section for example

**Comment by aarvndhNG** [comment]
> @ACaiCat can you add section by section like blocks are subtracted and weapons are subtracted like that

Ok @ACaiCat also can you do this to please

**Comment by ACaiCat** [comment]
OK
&nbsp;


me
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "That ***@***.***&gt;; 
发送时间: 2023年1月7日(星期六) 晚上11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Leader-txt/TShockPlugin-Shop] Error  (Issue #11)





  
@ACaiCat can you add section by section like blocks are subtracted and weapons are subtracted like that
  
Ok @ACaiCat also can you do this to please

**Comment by aarvndhNG** [comment]
> OK &nbsp; me ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "That ***@***.***&gt;; 发送时间: 2023年1月7日(星期六) 晚上11:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Leader-txt/TShockPlugin-Shop] Error (Issue #11) @ACaiCat can you add section by section like blocks are subtracted and weapons are subtracted like that Ok @ACaiCat also can you do this to please — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

@ACaiCat can you update this plugin UserSpecificFunctions

**Comment by ACaiCat** [comment]
> @ACaiCat can you update this plugin UserSpecificFunctions

@imnagarajan Could you elaborate on that?

**Comment by aarvndhNG** [comment]
> > @ACaiCat can you update this plugin UserSpecificFunctions
> 
> @imnagarajan Could you elaborate on that?

Ok sorry when I get the shop plugin

**Comment by aarvndhNG** [comment]
> > @ACaiCat can you update this plugin UserSpecificFunctions
> 
> @imnagarajan Could you elaborate on that?

Iam very very sorry

**Comment by aarvndhNG** [comment]
> > > @ACaiCat can you update this plugin UserSpecificFunctions
> > 
> > 
> > @imnagarajan Could you elaborate on that?
> 
> Iam very very sorry

When i get the new release

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by ACaiCat** [comment]
> When i get the new release

Maybe the day after tommorrow,I have classes this week.

**Comment by aarvndhNG** [comment]
> > When i get the new release
> 
> Maybe the day after tommorrow,I have classes this week.

Ok @ACaiCat

**Comment by aarvndhNG** [comment]
Sorry to ask this because i really need the shop for my server so please fix it @ACaiCat

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by sgkoishi** [comment]
[OOM is likely caused by mobile players](https://github.com/sgkoishi/yaaiomni/blob/a9738ccc1d1e5b0a9c20535cee132d0587f8bafc/src/Config.cs#L275-L285).
