### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by aarvndhNG** [Leader-txt/TShockPlugin-Shop#4]
Please update the plugin

**Comment by Leader-txt** [comment]
Sorry my friend,but I'm a little bit busy these days,so can you help me adapte this plugin to 1.4.4.9 and make a pull request for me?

**Comment by aarvndhNG** [comment]
> Sorry my friend,but I'm a little bit busy these days,so can you help me adapte this plugin to 1.4.4.9 and make a pull request for me?

Yes, i really  want to help but i don't have pc

**Comment by aarvndhNG** [comment]
That's why iam asking to you if i have pc I'll upgrade to 1.4.4.9

**Comment by Leader-txt** [comment]
Shame! Wait a minute for me to upgrade it.

**Comment by aarvndhNG** [comment]
> Shame! Wait a minute for me to upgrade it.

Thanks and sorry i can't upgrade

**Comment by Leader-txt** [comment]
> > Shame! Wait a minute for me to upgrade it.
> 
> Thanks and sorry i can't upgrade

You're welcome,my friend is adapting now , you'll no longer see the newest release

**Comment by aarvndhNG** [comment]
> > > Shame! Wait a minute for me to upgrade it.
> > 
> > 
> > Thanks and sorry i can't upgrade
> 
> You're welcome,my friend is adapting now , you'll no longer see the newest release

Why

**Comment by Leader-txt** [comment]
> 

Sorry , 'no longer' should be 'soon'.

**Comment by aarvndhNG** [comment]
> > 
> 
> Sorry , 'no longer' should be 'soon'.

Oh XD

**Comment by Leader-txt** [comment]
The newest release which has adapted to the newest version of TShock has been released.

**Comment by aarvndhNG** [comment]
> The newest release which has adapted to the newest version of TShock has been released.

Can you make it in English i can't understand Japanese

**Comment by ACaiCat** [comment]
> > The newest release which has adapted to the newest version of TShock has been released.
> 
> Can you make it in English i can't understand Japanese

It's already midnight in China(We should have a rest).And that is Chinese not Japanese.  :)

**Comment by aarvndhNG** [comment]
> > > The newest release which has adapted to the newest version of TShock has been released.
> > 
> > 
> > Can you make it in English i can't understand Japanese
> 
> It's already midnight in China(We should have a rest).And that is Chinese not Japanese. :)

Oh sorry i can't understand ok good night

**Comment by aarvndhNG** [comment]
Can you make the to English

**Comment by ACaiCat** [comment]
Jsut "Shop"?

**Comment by aarvndhNG** [comment]
> Jsut "Shop"?

Yes

**Comment by aarvndhNG** [comment]
![Uploading Screenshot_20221231-153422.png…]()

**Comment by aarvndhNG** [comment]
![Screenshot_20221231-153422](https://user-images.githubusercontent.com/107058543/210132750-2bd7b55b-02c4-475b-aa92-944dfc630f1f.png)

**Comment by ACaiCat** [comment]
> ![Screenshot_20221231-153422](https://user-images.githubusercontent.com/107058543/210132750-2bd7b55b-02c4-475b-aa92-944dfc630f1f.png)
> 

Try again?

**Comment by aarvndhNG** [comment]
> 

No

**Comment by aarvndhNG** [comment]
> > 
> 
> No

Pls make it English

**Comment by aarvndhNG** [comment]
@ACaiCat

**Comment by ACaiCat** [comment]
Ok, wait a minute.

**Comment by ACaiCat** [comment]
> @ACaiCat


Try the latest release :)

**Comment by aarvndhNG** [comment]
> > @ACaiCat
> 
> Try the latest release :)

Thanks so so so much
